"""Create transaction_data table

Revision ID: d2f881075bb9
Revises: 99fd866c66bf
Create Date: 2025-03-11 06:18:09.041228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f881075bb9'
down_revision: Union[str, None] = '99fd866c66bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_data_id'), 'trade_data', ['id'], unique=False)
    op.create_table('transaction_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_data_id'), 'transaction_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_data_id'), table_name='transaction_data')
    op.drop_table('transaction_data')
    op.drop_index(op.f('ix_trade_data_id'), table_name='trade_data')
    op.drop_table('trade_data')
    # ### end Alembic commands ###
